In [1]:
from scipy.linalg import qr
import numpy as np
from scipy.linalg import lstsq

In [2]:
A = [[1,0,1], [1,-1,18], [-2,0,-1], [1,-11,-1]]#matriz A gerada no SageMath
b = [[-1, -1, 0, 5]]#vetor b gerado no SageMath
Q, R = qr(A)#Factorização QR onde se obtém Matriz ortonormada Q e matriz triangular superior R

In [5]:
print(f"Matriz Q:\n{Q}")
print(f"Matriz R:\n{R}")

Matriz Q:
[[-0.37796447 -0.17021705  0.14308458 -0.89871899]
 [-0.37796447 -0.07092377 -0.92274779  0.02547915]
 [ 0.75592895  0.34043409 -0.34788852 -0.43777806]
 [-0.37796447  0.922009    0.08388616 -0.00231629]]
Matriz R:
[[ -2.64575131   4.53557368  -7.55928946]
 [  0.         -10.07117528  -2.709288  ]
 [  0.           0.         -16.20237333]
 [  0.           0.           0.        ]]


In [6]:
b=np.transpose(b)#transpor b para ficar 4x1
print(b)

[[-1]
 [-1]
 [ 0]
 [ 5]]


In [7]:
Qtb= np.transpose(Q) @ b #operação Q^T * b
print(Qtb)

[[-1.13389342]
 [ 4.85118584]
 [ 1.19909402]
 [ 0.86165841]]


In [8]:
x = lstsq(R, Qtb)#Solução final usando a função lstsq que da output da solução dos minimos quadrados para Ax=b,
                 #Neste caso Rx=Q^T * b

In [9]:
print(x[0])#O output da função são 4 arrays, no caso queremos o primeiro que respresenta a solução de x

[[-0.15160392]
 [-0.46178113]
 [-0.07400731]]
